add:	BinarySearch.c LinearSearch.c MergeSort.c PrintArray.c QuickSort.c SortingAndSearching.h sorting.c setArray.c
	gcc -c BinarySearch.c 
	gcc -c LinearSearch.c 
	gcc -c MergeSort.c 
	gcc -c PrintArray.c 
	gcc -c QuickSort.c
	gcc -c sorting.c 
	gcc -c setArray.c
	ar -cvr libmyG.a BinarySearch.o LinearSearch.o MergeSort.o PrintArray.o QuickSort.o sorting.o setArray.o
